In [1]:
# 안보고 Pandas 메서드 모두 사용해보기
import pandas as pd

df = pd.read_csv('../data/heart.csv')
df.head(10)

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1

In [2]:
df.shape

(303, 14)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trtbps    303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalachh  303 non-null    int64
 8   exng      303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64
 11  caa       303 non-null    int64
 12  thall     303 non-null    int64
 13  output    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [4]:
df.isna().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [5]:
df.dropna()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [6]:
df.fillna(df.mean())

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [7]:
df.describe()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [8]:
features = df.columns.tolist()

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_df = df.copy()
scaled_df[features] = scaler.fit_transform(df[features])
scaled_df

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,0.708333,1.0,1.000000,0.481132,0.244292,1.0,0.0,0.603053,0.0,0.370968,0.0,0.00,0.333333,1.0
1,0.166667,1.0,0.666667,0.339623,0.283105,0.0,0.5,0.885496,0.0,0.564516,0.0,0.00,0.666667,1.0
2,0.250000,0.0,0.333333,0.339623,0.178082,0.0,0.0,0.770992,0.0,0.225806,1.0,0.00,0.666667,1.0
3,0.562500,1.0,0.333333,0.245283,0.251142,0.0,0.5,0.816794,0.0,0.129032,1.0,0.00,0.666667,1.0
4,0.583333,0.0,0.000000,0.245283,0.520548,0.0,0.5,0.702290,1.0,0.096774,1.0,0.00,0.666667,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,0.583333,0.0,0.000000,0.433962,0.262557,0.0,0.5,0.396947,1.0,0.032258,0.5,0.00,1.000000,0.0
299,0.333333,1.0,1.000000,0.150943,0.315068,0.0,0.5,0.465649,0.0,0.193548,0.5,0.00,1.000000,0.0
300,0.812500,1.0,0.000000,0.471698,0.152968,1.0,0.5,0.534351,0.0,0.548387,0.5,0.50,1.000000,0.0
301,0.583333,1.0,0.000000,0.339623,0.011416,0.0,0.5,0.335878,1.0,0.193548,0.5,0.25,1.000000,0.0
302,0.583333,0.0,0.333333,0.339623,0.251142,0.0,0.0,0.786260,0.0,0.000000,0.5,0.25,0.666667,0.0

In [10]:
import numpy as np
np.sort(df['age'].unique())

array([29, 34, 35, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 74, 76, 77])

In [11]:
df['age'].value_counts(ascending=True)

29     1
74     1
76     1
77     1
37     2
34     2
38     3
69     3
71     3
40     3
70     4
68     4
35     4
39     4
47     5
49     5
46     7
48     7
50     7
66     7
43     8
65     8
61     8
53     8
42     8
45     8
55     8
67     9
63     9
41    10
64    10
56    11
60    11
44    11
62    11
51    12
52    13
59    14
54    16
57    17
58    19
Name: age, dtype: int64

In [12]:
df.iloc[1:4]
df[['age','sex','cp']]

     age  sex  cp
0     63    1   3
1     37    1   2
2     41    0   1
3     56    1   1
4     57    0   0
..   ...  ...  ..
298   57    0   0
299   45    1   3
300   68    1   0
301   57    1   0
302   57    0   1

[303 rows x 3 columns]

In [13]:
df.loc[2:4, ['age','sex']]

   age  sex
2   41    0
3   56    1
4   57    0

In [14]:
tmp = df[(df['age']>=60) & (df['sex']==0)]

In [15]:
tmp.sort_values(by='chol', ascending=False)

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2,1
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3,0
96,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1
39,65,0,2,160,360,0,0,151,0,0.8,2,0,2,1
182,61,0,0,130,330,0,0,169,0,0.0,2,0,2,0
110,64,0,0,180,325,0,1,154,1,0.0,2,0,2,1
82,60,0,2,102,318,0,1,160,0,0.0,2,1,2,1
112,64,0,2,140,313,0,1,133,0,0.2,2,0,3,1
213,61,0,0,145,307,0,0,146,1,1.0,1,0,3,0
120,64,0,0,130,303,0,1,122,0,2.0,1,2,2,1
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1
252,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
153,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1
127,67,0,2,152,277,0,1,172,0,0.0,2,1,2,1
263,63,0,0,108,269,0,1,169,1,1.8,1,2,2,0
38,65,0,2,155,269,0,1,148,0,0.8,2,0,2,1
129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
167,62,0,0,140,268,0,0,160,0,3.6,0,2,2,0
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1
216,62,0,2,130,263,0,1,97,0,1.2,1,1,3,0
207,60,0,0,150,258,0,0,157,0,2.6,1,2,3,0
54,63,0,2,135,252,0,0,172,0,0.0,2,0,2,1
258,62,0,0,150,244,0,1,154,1,1.4,1,0,2,0
147,60,0,3,150,240,0,1,171,0,0.9,2,0,2,1
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1
260,66,0,0,178,228,1,1,165,1,1.0,1,2,3,0
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1
181,65,0,0,150,225,0,0,114,0,1.0,1,3,3,0
143,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1
105,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1
69,62,0,0,124,209,0,1,163,0,0.0,2,0,2,1
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
102,63,0,1,140,195,0,1,179,0,0.0,2,2,2,1
136,60,0,2,120,178,1,1,96,0,0.0,2,0,2,1
204,62,0,0,160,164,0,0,145,0,6.2,0,3,3,0
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1

In [16]:
tmp.rename(columns={'age':'age', 'sex':'gender'})

,age,gender,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2,1
38,65,0,2,155,269,0,1,148,0,0.8,2,0,2,1
39,65,0,2,160,360,0,0,151,0,0.8,2,0,2,1
54,63,0,2,135,252,0,0,172,0,0.0,2,0,2,1
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1
69,62,0,0,124,209,0,1,163,0,0.0,2,0,2,1
82,60,0,2,102,318,0,1,160,0,0.0,2,1,2,1
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1
96,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1
102,63,0,1,140,195,0,1,179,0,0.0,2,2,2,1
105,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1
110,64,0,0,180,325,0,1,154,1,0.0,2,0,2,1
112,64,0,2,140,313,0,1,133,0,0.2,2,0,3,1
120,64,0,0,130,303,0,1,122,0,2.0,1,2,2,1
127,67,0,2,152,277,0,1,172,0,0.0,2,1,2,1
129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
136,60,0,2,120,178,1,1,96,0,0.0,2,0,2,1
143,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
147,60,0,3,150,240,0,1,171,0,0.9,2,0,2,1
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1
153,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1
167,62,0,0,140,268,0,0,160,0,3.6,0,2,2,0
181,65,0,0,150,225,0,0,114,0,1.0,1,3,3,0
182,61,0,0,130,330,0,0,169,0,0.0,2,0,2,0
204,62,0,0,160,164,0,0,145,0,6.2,0,3,3,0
207,60,0,0,150,258,0,0,157,0,2.6,1,2,3,0
213,61,0,0,145,307,0,0,146,1,1.0,1,0,3,0
216,62,0,2,130,263,0,1,97,0,1.2,1,1,3,0
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3,0
252,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
258,62,0,0,150,244,0,1,154,1,1.4,1,0,2,0
260,66,0,0,178,228,1,1,165,1,1.0,1,2,3,0
263,63,0,0,108,269,0,1,169,1,1.8,1,2,2,0
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0

In [17]:
tmp['tmp'] = 10

<ipython-input-17-8cb0123c5805>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp['tmp'] = 10

In [18]:
tmp.drop(['tmp'], axis=1)

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2,1
38,65,0,2,155,269,0,1,148,0,0.8,2,0,2,1
39,65,0,2,160,360,0,0,151,0,0.8,2,0,2,1
54,63,0,2,135,252,0,0,172,0,0.0,2,0,2,1
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1
69,62,0,0,124,209,0,1,163,0,0.0,2,0,2,1
82,60,0,2,102,318,0,1,160,0,0.0,2,1,2,1
85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1
96,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1
102,63,0,1,140,195,0,1,179,0,0.0,2,2,2,1
105,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1
110,64,0,0,180,325,0,1,154,1,0.0,2,0,2,1
112,64,0,2,140,313,0,1,133,0,0.2,2,0,3,1
120,64,0,0,130,303,0,1,122,0,2.0,1,2,2,1
127,67,0,2,152,277,0,1,172,0,0.0,2,1,2,1
129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1
136,60,0,2,120,178,1,1,96,0,0.0,2,0,2,1
143,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1
144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1
147,60,0,3,150,240,0,1,171,0,0.9,2,0,2,1
151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1
153,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1
167,62,0,0,140,268,0,0,160,0,3.6,0,2,2,0
181,65,0,0,150,225,0,0,114,0,1.0,1,3,3,0
182,61,0,0,130,330,0,0,169,0,0.0,2,0,2,0
204,62,0,0,160,164,0,0,145,0,6.2,0,3,3,0
207,60,0,0,150,258,0,0,157,0,2.6,1,2,3,0
213,61,0,0,145,307,0,0,146,1,1.0,1,0,3,0
216,62,0,2,130,263,0,1,97,0,1.2,1,1,3,0
220,63,0,0,150,407,0,0,154,0,4.0,1,3,3,0
252,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
258,62,0,0,150,244,0,1,154,1,1.4,1,0,2,0
260,66,0,0,178,228,1,1,165,1,1.0,1,2,3,0
263,63,0,0,108,269,0,1,169,1,1.8,1,2,2,0
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0

In [30]:
tmp = tmp.sort_values(by='age')
new = tmp[['age']]
new.reset_index(inplace=True)
tmp.reset_index(inplace=True)

new['Age'] = 100

<ipython-input-30-64c82bc172e6>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['Age'] = 100

tmp.merge(new, on=index, how='left)

In [32]:
tmp.merge(new, on='index', how='left')

,index,age_x,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output,tmp,age_y,Age
0,147,60,0,3,150,240,0,1,171,0,0.9,2,0,2,1,10,60,100
1,207,60,0,0,150,258,0,0,157,0,2.6,1,2,3,0,10,60,100
2,136,60,0,2,120,178,1,1,96,0,0.0,2,0,2,1,10,60,100
3,82,60,0,2,102,318,0,1,160,0,0.0,2,1,2,1,10,60,100
4,182,61,0,0,130,330,0,0,169,0,0.0,2,0,2,0,10,61,100
5,213,61,0,0,145,307,0,0,146,1,1.0,1,0,3,0,10,61,100
6,167,62,0,0,140,268,0,0,160,0,3.6,0,2,2,0,10,62,100
7,258,62,0,0,150,244,0,1,154,1,1.4,1,0,2,0,10,62,100
8,204,62,0,0,160,164,0,0,145,0,6.2,0,3,3,0,10,62,100
9,252,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0,10,62,100
10,69,62,0,0,124,209,0,1,163,0,0.0,2,0,2,1,10,62,100
11,96,62,0,0,140,394,0,0,157,0,1.2,1,0,2,1,10,62,100
12,216,62,0,2,130,263,0,1,97,0,1.2,1,1,3,0,10,62,100
13,263,63,0,0,108,269,0,1,169,1,1.8,1,2,2,0,10,63,100
14,296,63,0,0,124,197,0,1,136,1,0.0,1,0,2,0,10,63,100
15,220,63,0,0,150,407,0,0,154,0,4.0,1,3,3,0,10,63,100
16,54,63,0,2,135,252,0,0,172,0,0.0,2,0,2,1,10,63,100
17,102,63,0,1,140,195,0,1,179,0,0.0,2,2,2,1,10,63,100
18,110,64,0,0,180,325,0,1,154,1,0.0,2,0,2,1,10,64,100
19,112,64,0,2,140,313,0,1,133,0,0.2,2,0,3,1,10,64,100
20,120,64,0,0,130,303,0,1,122,0,2.0,1,2,2,1,10,64,100
21,181,65,0,0,150,225,0,0,114,0,1.0,1,3,3,0,10,65,100
22,39,65,0,2,160,360,0,0,151,0,0.8,2,0,2,1,10,65,100
23,38,65,0,2,155,269,0,1,148,0,0.8,2,0,2,1,10,65,100
24,28,65,0,2,140,417,1,0,157,0,0.8,2,1,2,1,10,65,100
25,260,66,0,0,178,228,1,1,165,1,1.0,1,2,3,0,10,66,100
26,17,66,0,3,150,226,0,1,114,0,2.6,0,0,2,1,10,66,100
27,153,66,0,2,146,278,0,0,152,0,0.0,1,1,2,1,10,66,100
28,143,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1,10,67,100
29,127,67,0,2,152,277,0,1,172,0,0.0,2,1,2,1,10,67,100
30,85,67,0,2,115,564,0,0,160,0,1.6,1,0,3,1,10,67,100
31,105,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1,10,68,100
32,19,69,0,3,140,239,0,1,151,0,1.8,2,2,2,1,10,69,100
33,151,71,0,0,112,149,0,1,125,0,1.6,1,0,2,1,10,71,100
34,60,71,0,2,110,265,1,0,130,0,0.0,2,1,2,1,10,71,100
35,25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1,10,71,100
36,129,74,0,1,120,269,0,0,121,1,0.2,2,1,2,1,10,74,100
37,144,76,0,2,140,197,0,2,116,0,1.1,1,0,2,1,10,76,100